services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: user_management
      POSTGRES_USER: "jjones"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - user-management-network

  redis:
    image: redis:6
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - user-management-network

networks:
  user-management-network:
    driver: bridge

volumes:
  pgdata:
